### ISSUE TITLE
语音文件为什么是raw格式的？我自己录制的mp3为什么无法识别？

### ISSUE THREAD

**Issue by hcsaaron** [zenny-chen/How-to-use-PocketSphinx-in-iOS#1]
您好！我最近也在研究Pocketsphinx，看了TLSphinx和您的demo，音频文件都是raw格式的，我无法打开raw格式的文件，更加无法播放该文件。而自己录制的mp3、mov、wav格式的文件均无法识别成功。麻烦提供下帮助，谢谢！

**Comment by zenny-chen** [comment]
因为做语音训练和识别时都需要且仅需要原始的PCM音频数据。因此如果您要用mp3文件的话也得自己做解码，转为PCM之后才能使用。
谢谢。

**Comment by zenny-chen** [comment]
因为做语音训练和识别时都需要且仅需要原始的PCM音频数据。因此如果您要用mp3文件的话也得自己做解码，转为PCM之后才能使用。
谢谢。
